### ISSUE TITLE
非常棒的设计，目前最接近理想的记账app，不过有几点小小的建议

### ISSUE THREAD

**Issue by PhenoGuan** [YeNomX/support#11]
1. 是否可以实现标签的二级分类，可以让用户自定义选择，否则标签数量太多，会影响记账效率；如果有违设计初衷的话，是否可以增加设置，选择标签时，可以选择按照首字母排列，或者按照标签被使用数量排列？

2. 点击单笔已记录账目时，可能是因为预留了照片的尺寸，是否可以自定适配这个部分的尺寸？如果记账没有添加照片的话，空白区域面积太大。

3. 是否有可能在首页显示下账户结余？比如在首页下方

4. 首页月份显示和手机顶层状态栏距离太远，可以增加一点安全距离，这样看起来更舒服。

5. 目前进入报表界面的操作稍显复杂，或者交互形式有些割裂。个人使用习惯上，相比设置、过滤等，报表使用频率还是比较高的。包括点击首页左下方绿点时候，出现的选择界面不够精致，和整体风格不搭。是否可以参考Spark手机客户端底部的快捷菜单的设计，或者有没有更好的设计，快速且高效？

**Comment by Kjuly** [comment]
Hi @PhenoGuan ，感谢你的建议，我会考虑的。:+1:

至于“标签的二级分类”，不知道你有没注意到类别这个功能，你可以创建一个新标签，在该标签未被任何记录使用的情况下，你可以点击该标签左侧的“+”，然后再选择其它想要 group 在一起的标签。比如你可以将 “Domain Name”, "License", "Software", "Server" 等标签 group 在 "Dev" 类下。

对了，标签管理页面以后会被单独拎出来的。

**Comment by PhenoGuan** [comment]
@Kjuly 谢谢你的回复！

刚刚我试用了一下，标签分类好之后（比如我把所有细项分了五类），在记账的时候，在屏幕靠下方的几个类别在点击展开的时候，界面直接跳到最上方了，算是个小BUG。不知道我描述的清楚不清楚。

**Comment by Kjuly** [comment]
描述得挺清楚的，我已经重现了，这个体验确实挺差的，我会修复的，感谢反馈。:+1:

**Comment by Kjuly** [comment]
**UPDATE**:

> 对了，标签管理页面以后会被单独拎出来的。  

> 刚刚我试用了一下，标签分类好之后（比如我把所有细项分了五类），在记账的时候，在屏幕靠下方的几个类别在点击展开的时候，界面直接跳到最上方了，算是个小BUG。不知道我描述的清楚不清楚。

在 v3.3.0 提供独立标签管理页面后，这块已经移除了类别管理 (v3.3.1)。

> 3. 是否有可能在首页显示下账户结余？比如在首页下方

最新释出的 v3.4.1 支持了 Widget，可以为时常关注的账户添加相应的报表。

Widget 预览：
<img width="412" alt="summarywidget_with_device" src="https://user-images.githubusercontent.com/867323/30916983-648367f6-a3cd-11e7-9b32-e892e962a0cb.png">

其它建议中的优化可能会在以后应用，就不在这讨论了。 😁
