### ISSUE TITLE
更新问题

### ISSUE THREAD

**Issue by skyarea** [YeNomX/support#12]
IOS10.3系统，更新到3.2.0版本后，点击图标打不开，卸载重现安装，还是无法打开
谢谢！

**Comment by Kjuly** [comment]
Hi @skyarea ，我现在用的 10.3.2 (14F89) 上没有这个问题。能否提供你的具体系统版本？还有设备型号？谢谢。:)

**Comment by skyarea** [comment]
系统也是 10.3.2（14F89），iPhone6 64G；如图，点击后会变成灰色，但是无法启动
![snipaste20170628_193023](https://user-images.githubusercontent.com/2284570/27635048-3a7368c6-5c38-11e7-87a9-bbb66a1a8fde.png)

**Comment by Kjuly** [comment]
@skyarea 噢，通过你提供的截图图标颜色，可能是由于应用没成功同步到设备的缘故，可以再尝试连接 iTunes 进行同步下试试，下下策就是重新启动下设备了。

**Comment by skyarea** [comment]
重新启动手机，可以使用了，谢谢

**Comment by Kjuly** [comment]
@skyarea 哈哈哈哈 😁
